name: iql
channels:
  - conda-forge
  - nvidia
dependencies:
  - python == 3.10
  - pip
  - numpy >= 1.20.2
  - scipy >= 1.6.0
  - absl-py >= 0.12.0
  - cython < 3
  - cffi
  - lockfile
  - pip:
    - gym[mujoco] >= 0.18.0
    - gdown >= 3.12.2
    - tqdm >= 4.60.0
    - ml_collections >= 0.1.0
    - tensorboardX == 2.1
    - tensorflow-probability >= 0.14.1
    - imageio >= 2.9.0
    - imageio-ffmpeg >= 0.4.3
    - protobuf < 3.20